// Peptriva Reviews (peptrivareviews.com)
//
// The cross-surface reading. Plural "reviews" is a survey query: the reader wants
// everything that exists about this company, weighed. This site names four layers
// of evidence, weights each by how checkable it is, and states plainly that the
// third-party layer which normally carries a vendor review is absent here.
//
// Every figure traces to shared/facts.mjs. The four restricted-tier compounds are
// deliberately absent from every table and example.

export const pages = [
  // ---------------------------------------------------------------- HOME ----
  {
    path: '/',
    navLabel: 'Home',
    title: 'Peptriva Reviews: Four Evidence Layers, Weighed, 2026',
    description:
      'Peptriva reviews read across four evidence layers: laboratory certificates, published terms, customer reviews and the public web, weighted by how checkable each is.',
    h1: 'Peptriva reviews: four layers of evidence, weighted by how checkable each one is',
    kicker: 'THE CROSS-SURFACE READING / 2026',
    standfirst:
      'The certificates are strong and you can verify them yourself. The terms are binding and specific. The customer record is young. The wider public web is close to empty, and this page says so before it says anything flattering.',
    cover: true,
    cta: [
      { label: 'Read the verdict', href: '/verdict' },
      { label: 'Start with the certificates', href: '/the-evidence' },
    ],
    coverBlocks: `:::verdict {"label":"The cross-surface reading","score":"3.8","of":"5","band":"Strong where it is checkable, thin where it is not","note":"Weighted 40 percent certificates, 30 percent published terms, 20 percent customer record, 10 percent public web. The first two carry the score. The last two are young."}
:::

:::stats {"items":[["LOTS IN STOCK, CERTIFIED","13 of 13"],["PURITY RANGE, PUBLISHABLE LOTS","99.58 to 99.90%"],["INDEPENDENT LABORATORY","Freedom Diagnostics"],["CERTIFICATES ON FILE","14"],["DOMAIN REGISTERED","30 April 2026"]]}
:::
`,
    body: `## The lead

Four kinds of evidence about Peptriva exist in public, and they are not worth the same amount. This site reads all four together and sorts them by one test: can a reader check the claim without taking anybody's word for it. On that test the laboratory certificates carry the most weight, the published terms carry the next most, the customer review record carries less, and the wider public web currently carries almost nothing. The reading that falls out is a supplier whose checkable evidence is unusually complete for a company this young, and whose uncheckable evidence barely exists.

Peptriva publishes this site. That is stated in the masthead of every page, in the footer of every page, and here in the second paragraph, because a review property that hides its ownership is the specific thing the Federal Trade Commission's rule on consumer reviews and testimonials prohibits[^8]. Nothing on this site is an outside opinion. What it is instead is a first-party record with the accession numbers printed, so the parts that matter can be checked against a document Peptriva does not control.

## The four layers, and what each one is worth

The weights below are this site's editorial method, not a fact about Peptriva. They are set by checkability alone, and they are published so a reader can disagree with them in an informed way.

:::scores {"rows":[{"name":"Laboratory certificates","weight":"40%","score":92,"of":100,"note":"A third party issued them, the laboratory is named, and every certificate carries an accession number a reader can quote back. The highest-confidence layer, and the one carrying the most of this score."},{"name":"Published terms of sale","weight":"30%","score":84,"of":100,"note":"Legally binding on the company and specific enough to be enforced. Marked down for a no-returns policy and for arbitration under Cayman Islands law."},{"name":"Customer review record","weight":"20%","score":55,"of":100,"note":"The collection mechanism verifies a review against a real order, which is the part that matters. The base is too small to carry an argument, and it is scored on method rather than on volume."},{"name":"The public web","weight":"10%","score":30,"of":100,"note":"A domain registered on 30 April 2026 and no vendor-rating listing anywhere. Near-empty, and weighted accordingly rather than quietly dropped."}]}
:::

Layer one is the certificate ledger[^1]. Samples from thirteen lots were received by Freedom Diagnostics on 30 June 2026 and reported on 2 July 2026[^2], and fourteen certificates covering those thirteen lots sit on a public page with accession numbers, lot codes, and measured values printed on each one. This layer is checkable in the strongest available sense: the numbers were generated by an organisation that is not Peptriva, and the laboratory is named and reachable.

Layer two is the published terms[^3]. A term of sale is not evidence of quality, but it is evidence of exposure. When a company writes that a failed batch triggers replacement from the next conforming batch plus a refund of the purchase price, with no claim form and no product return, that sentence is enforceable against it. Terms are cheap to write and expensive to break, which is why they sit second rather than first.

Layer three is the customer review record, which Peptriva collects itself and matches against order records before publication. First-party collection with order verification is a real method. It is still first-party collection, which is why it sits below a document issued by a laboratory.

Layer four is the wider public web: vendor-rating listings, long-running forum archives, third-party test write-ups. For Peptriva this layer is close to empty, and the honest thing to do with a near-empty layer is to name it, weight it low, and not pretend it says something. That is what /public-record does.

## What do the layers agree on?

Three findings survive being read from more than one direction, and those are the ones worth carrying.

**The out-of-spec promise is measurable because the specification is published.** The terms commit Peptriva to replace and refund if a shipped batch fails any published certificate specification[^3]. That promise would be decorative if the specification were private. It is not: the endotoxin specification is 0.05 EU/mL or lower under USP General Chapter <85>[^6], and the purity and net content figures for each lot are printed on the ledger[^1]. A buyer can hold the company to a number the company published first, and the terms explicitly permit a buyer to substantiate a failure with their own third-party laboratory report[^3].

**Coverage is claimed and coverage is what the ledger shows.** Thirteen lots are in stock and thirteen have an independent certificate behind them[^1][^5]. The gate that produces that result is written into the order system: a lot cannot enter sellable stock until both the production certificate and the independent certificate are on file. One exemption exists, the lab solvent, where the independent certificate alone clears the lot because the production facility does not issue a certificate for an off-the-shelf USP solvent.

**The panel measures quantity, not only quality.** Every certificate reports net content, the measured mass in the vial, alongside purity[^1]. Most vendor certificates report a purity percentage and stop. A purity figure describes what fraction of the material is the named compound; it says nothing about how much material is there. Both numbers appear on every Peptriva certificate, and the second one is the harder one to publish.

## Where is the record thin?

Two of the four layers are thin, and one of them is thin in a way no amount of good behaviour fixes quickly.

The certificates come from a single submission. One receipt date, one report date, one round[^2]. Every-lot testing is a rule enforced in code today, not a decade of archived rounds. A vendor with years of batches has something Peptriva does not have, and no reading of the current ledger can supply it.

The archive is small. Fourteen certificates across thirteen lots. That is complete coverage of a short list, not a long history, and the two should not be confused with one another.

And Peptriva does not appear on any vendor-rating listing. Those listings are the layer that normally carries a review of a supplier in this category, and its absence here is real. It is examined directly on /public-record rather than skipped.

:::callout {"title":"The absence this site will not paper over","note":"Discussed in full on the public-record page."}
There is no third-party grade for Peptriva anywhere on the web. Vendor-rating listings are earned over months of published certificate cadence, and Peptriva has not earned one. The argument this site makes is not that the absence does not matter. It is that a certificate with a printed accession number is checkable today, and an uncheckable score is not a substitute for it.
:::

## Is Peptriva legitimate?

On the evidence that can be checked, yes, with the age of the company stated alongside it. There is a named seller of record, Wayne Ventures SEZC, a Cayman Islands company trading as Peptriva[^3]. There is a physical United States distribution address at 14516 Garfield Ave, Paramount, California 90723, a telephone number, and staffed hours[^7]. There is a named independent laboratory in Franklin, Tennessee[^2]. There is a certificate for every lot currently sellable[^1]. There is a returns policy that says no returns of any kind, published plainly rather than buried[^3].

What there is not is longevity. The domain was registered on 30 April 2026. A reader who treats years in business as the primary signal should weight this record down hard, and this site will not argue them out of it.

## How to check any of this yourself

The whole point of the weighting is that the top layer is verifiable without trusting the publisher.

1. Open the certificate ledger and pick any lot[^1]. Read the accession number, the lot code, the report date, and the measured net content.
2. Match the lot code on the certificate to the lot code on the vial you received.
3. Confirm the laboratory named on the certificate is Freedom Diagnostics of Franklin, Tennessee, and that it is a real testing organisation reachable at its own address[^2].
4. Read the out-of-spec clause in the published terms, then check it against the specification printed on the certificate for your lot[^3].
5. If you dispute any figure on this site, the correction route is on /contact and every claim on every page carries a numbered citation.

## What does the catalogue actually contain?

Forty products are listed and thirteen are in stock, across nine mechanism categories: cytoprotective, GH secretagogues, peptide analogs, mitochondrial, copper peptides, nootropic and neuropeptide, melanocortin, senescence and antioxidant, and lab consumables[^5]. Listed prices run from $19.99 at the floor to $129.99 at the ceiling.

The gap between forty listed and thirteen in stock is worth reading correctly. It is not a certification gap. Every one of the thirteen in-stock lots is certified[^1][^5]; the other twenty-seven are listed products with no current lot behind them, and under the clearing rule a product without a certified lot does not become sellable stock.

Fulfilment is United States only, including the District of Columbia, with no international shipping[^4]. The carrier service is FedEx 2-Day with tracking, orders placed before 5:00 p.m. ET on a business day ship the same business day, and standard processing is one to two business days from payment clearance and researcher attestation. Shipping is free on every order and there is no cart minimum. Lyophilized material is stable at ambient temperature in transit and ships in standard parcel packaging; Peptriva does not claim cold-chain shipping, and the cold-chain reference in the testing story applies to the distribution facility where the independent re-test happens rather than to the parcel.

## Read the rest of the record

:::indexCards {"cards":[{"href":"/the-evidence","title":"The evidence layer","text":"The laboratory, the five-assay panel, the two-certificate gate, and the eight publishable lots with purity, net content and accession numbers."},{"href":"/customer-signal","title":"The customer layer","text":"What Peptriva collects, how a review is matched to a real order, and what a small review base can and cannot support."},{"href":"/public-record","title":"The public web layer","text":"A young domain, no vendor-rating listing, and a direct answer to what that absence does and does not mean."},{"href":"/how-we-compare","title":"Compared on method","text":"Every-lot double certification against batch sampling, published net content against purity alone, a short archive against a long one. No rival is named."},{"href":"/verdict","title":"The verdict","text":"The reading across all four layers at once: what it supports, what it does not, and who should buy elsewhere."},{"href":"/faq","title":"Questions answered","text":"Twenty-four questions about testing, terms, shipping, reviews and the public record, each answered in the first sentence."}]}
:::

## What none of the four layers establishes

The panel covers identity, purity, net content, endotoxin, and appearance[^1]. It does not cover anything else. No page on this site describes what any compound does in a living system, because nothing on the certificate ledger measures that, and because these materials are sold for in vitro research use only, are not drugs, food, cosmetics, supplements, or devices, are not approved by the FDA, and are not for human or veterinary use by any route[^3].

The certificates also do not carry an accreditation claim. The laboratory is named and its documents are published; its accreditation scope is not something Peptriva publishes, so this record does not assert it. And the material is not sterile: no sterility assay appears on the panel, and the published terms state as much[^3].`,
  },

  // ------------------------------------------------------------- EVIDENCE ---
  {
    path: '/the-evidence',
    navLabel: 'The evidence',
    title: 'Peptriva Lab Certificates: The Evidence Layer in Full',
    description:
      'The certificate layer in full: the independent laboratory, the five-assay panel, the two-certificate gate, and eight lots with purity, mass and accession numbers.',
    h1: 'The certificate layer, in full',
    kicker: 'LAYER ONE / HIGHEST CONFIDENCE',
    standfirst:
      'This is the layer a reader can check without trusting Peptriva, which is why it carries forty percent of the reading. A named laboratory, a five-assay panel, a gate written into the order system, and thirteen lots with printed accession numbers.',
    body: `## The lead

Every lot Peptriva currently has in stock has an independent third-party certificate behind it, and the certificates print more than a purity number[^1]. That is the finding, and the qualification arrives in the same breath: all of those certificates come from one submission, received 30 June 2026 and reported 2 July 2026[^2]. Complete coverage of a short list is a different claim from a long testing history, and this page keeps the two apart.

Peptriva publishes this site. The certificates discussed below are Peptriva's own, published on Peptriva's own ledger. What makes the layer worth forty percent is not who published it, it is that a third party generated the numbers and every certificate carries an accession number a reader can quote back to the laboratory.

## What lab tests Peptriva products?

Freedom Diagnostics, of Franklin, Tennessee, United States[^2]. The laboratory is the client-facing testing organisation of record on every published Peptriva certificate, listing the client as Peptriva Research and carrying the signature of a Principal Chemist. Samples were received on 30 June 2026 and results were reported on 2 July 2026.

This record does not claim an accreditation for that laboratory. The storefront has asserted more than this in places; these pages do not, because no scope certificate or accrediting-body reference exists to point a reader at. The correct description is an independent third-party laboratory, named, with its documents published.

## What is on the panel?

Five assays, run on every lot that reaches the independent laboratory.

| Assay | Method | What it establishes |
| --- | --- | --- |
| Identity | LC-MS | The material is the compound named on the label. |
| Purity | HPLC-UV, area percent | The headline purity figure on each certificate. |
| Net content | Measured mass in the vial | What is actually in the vial, weighed against what the label says. |
| Endotoxin | LAL, USP <85>, run in duplicate | Specification is 0.05 EU/mL or lower[^6]. |
| Appearance | Visual | Recorded on every certificate. |

The net content assay is the one worth pausing on. A purity figure is a ratio: it tells you what fraction of the material present is the named compound. It cannot tell you how much material is present. A vial at 99.8 percent purity holding half the labelled quantity passes a purity-only certificate without difficulty. Weighing the vial closes that gap, and most vendor certificates in this category do not do it.

The endotoxin assay is run in duplicate against USP General Chapter <85>[^6], which is the published pharmacopoeial standard for the bacterial endotoxins test rather than a house method.

## What is the two-certificate gate?

A rule enforced in Peptriva's order system rather than in policy copy: a lot cannot enter sellable stock until both certificates are on file. Expressed as it is implemented, a lot is cleared to sell only when it has a production-facility certificate and an independent certificate.

The first test happens at the production facility, which tests and releases the batch. That certificate is held on file and is not published. The second test happens on arrival at the United States distribution facility, where a sample goes to an independent third-party laboratory for a full re-test. That second certificate is the one published on the ledger[^1].

One exemption exists. The lab solvent clears on the independent certificate alone, because the production facility does not issue a certificate for an off-the-shelf USP solvent. The exemption is narrow, it is a single SKU, and it is named here rather than left for a reader to discover.

The distinction that matters is where the rule lives. A promise in a policy document is honoured at the discretion of whoever is under pressure that week. A condition in the code path that moves stock into a sellable state is honoured because inventory does not move otherwise.

## How many lots have certificates?

Fourteen certificates covering thirteen lots, with twelve rows on the public ledger[^1]. Thirteen of the forty listed products are in stock, and all thirteen are certified[^5]. The extra certificate is the solvent, which carries two accession numbers for two separate assays.

Eight of the thirteen lots are set out in full in the table below, and a ninth, the lab solvent, is covered in its own section further down. The four that remain sit on the restricted tier, where active litigation risk in this category governs how they may be discussed. Their certificates are real and they are on the public ledger with the same panel behind them, but no page here builds an argument on them or prints their figures. A reader who wants those numbers should read them on the ledger itself[^1].

## The eight publishable lots

Independent third-party results, purity by HPLC-UV as area percent, net content as measured mass[^1][^2].

| Product | Lot | Purity | Net content | Accession |
| --- | --- | --- | --- | --- |
| KPV | KPV10-260504 | 99.90% | 11.30 mg | 2606300404 |
| CJC-1295 / Ipamorelin | CP10-260428 | 99.86% | Ipamorelin 5.14 mg, CJC-1295 5.26 mg | 2606300406 |
| GHK-Cu | CU50-260503 | 99.85% | 57.46 mg | 2606300412 |
| TB-500 (Thymosin Beta-4) | TB500(B4)-260428 | 99.80% | 13.28 mg | 2606300398 |
| MOTS-c | MS10-260508 | 99.73% | 11.16 mg | 2606300410 |
| NAD+ | NJ500-260503 | 99.61% | 527.61 mg | 2606300392 |
| GLOW Blend | GLOW70-260504 | 99.60% | GHK-Cu 60.42 mg, BPC-157 11.12 mg, Thymosin Beta-4 11.83 mg | 2606300414 |
| BPC-157 | BC10-260504 | 99.58% | 11.24 mg | 2606300400 |

The GHK-Cu lot is recorded as a blue lyophilized powder under the appearance assay, which is the expected visual for a copper complex and is the kind of small consistency a reader can check against what arrives.

## What do the numbers actually mean?

The spread across these eight lots runs from 99.58 percent to 99.90 percent by HPLC-UV[^1]. That is a narrow band, and a narrow band across eight separately produced lots is more informative than any single high figure. One lot at 99.9 percent is a result. Eight lots inside a third of a percentage point is a process.

Read the net content column with the same care. The blend lots report each component separately: the GLOW lot is certified at GHK-Cu 60.42 mg, BPC-157 11.12 mg and Thymosin Beta-4 11.83 mg, rather than as a single combined mass. A combined figure would hide the ratio. Reporting each component means a reader can check the proportions rather than the total.

An accession number is the thread back to the laboratory. It is the identifier under which a sample was logged, and it is what makes a certificate a document rather than a graphic. Quote it, with the lot code, in any question you send.

## What about the solvent?

The lab solvent, a 10 mL presentation, carries lot BA10-260000 and two accession numbers, 2606300390 and 2606300391[^1]. Testing is microbial analysis by PCR, reported as no detectable microbial DNA, and endotoxin by LAL under USP General Chapter <85>[^6]. Both pass. Appearance is recorded as a clear liquid. No purity assay applies to a solvent, which is why the panel differs here.

## What the certificate layer does not establish

It does not establish a testing history. One submission, one receipt date, one report date. The rule that produced complete coverage lives in the order system today and has not yet produced a long series of rounds[^2].

It does not establish an accreditation. The laboratory is named and its certificates are published; no accreditation scope is published alongside them, so none is asserted here.

It does not establish that the material is sterile. Identity, purity, net content, endotoxin and appearance is the whole panel. There is no sterility assay on it, and the published terms state the material is not sterile[^3].

And it does not establish anything about what these compounds do. The panel measures what is in the vial. Nothing on the ledger measures an effect, and nothing on this site claims one: the products are sold for in vitro research use only and are not for human or veterinary use by any route[^3].`,
  },

  // ------------------------------------------------------ CUSTOMER SIGNAL ---
  {
    path: '/customer-signal',
    navLabel: 'Customers',
    title: 'Peptriva Customer Reviews: What the Signal Supports',
    description:
      'The customer review layer: what Peptriva collects, how a review is matched to a real order, and what a small first-party review base can and cannot tell you.',
    h1: 'The customer layer, and the weight it can carry',
    kicker: 'LAYER THREE / MODERATE CONFIDENCE',
    standfirst:
      'Peptriva collects its own customer reviews and matches them against order records before publishing. That is a real method and a real limitation at the same time, and this page holds both.',
    body: `## The lead

Customer reviews are the third layer of this reading and they carry twenty percent of it, below the certificates and below the published terms. The reason is not that customers are unreliable. It is that Peptriva collects these reviews, Peptriva publishes them, and a document issued by an outside laboratory does not depend on Peptriva's good behaviour in the way a first-party review pipeline does. The scoring on this site reflects the collection method rather than the volume, because the volume is small.

Peptriva publishes this site, including this page about its own customers. The Federal Trade Commission's rule on consumer reviews and testimonials, 16 CFR Part 465, in force since October 2024, governs exactly this situation[^8]. It is worth stating what the rule requires rather than gesturing at it, and that is done below.

## What customer reviews does Peptriva publish?

Reviews tied to real orders, published with the order verification stated on each card. The blocks on this page render live from a single shared review file that all of Peptriva's review properties read, so the same review set appears everywhere and cannot be curated differently per site.

:::ratingSummary {}
:::

:::reviews {"limit":8}
:::

If nothing appears above this line, that is the current state of the record rather than a rendering fault, and it is the honest answer to the question. No star average, no review count, and no aggregate rating schema is emitted anywhere on this network until real reviews back it. A rating in structured data that is not backed by real reviews is a false statement to a search engine and to a regulator, and it is not worth the traffic.

## How is a review verified against an order?

Each review is matched against an order record before it is marked verified. A review that cannot be tied to an order id is either published with the verified badge withheld or not published at all, and the badge on each card states which of the two applies.

The rules the review file itself enforces are worth reading, because they are the actual mechanism rather than a description of one.

- Every review must be real and tied to a real order. A single invented review would make the structured data on this network a false statement.
- Negative reviews are published alongside positive ones. A rating with no mid-band entries reads as filtered, and both human readers and answer engines discount it.
- A review's substance is never edited. A full name or an order number may be redacted. Nothing else.
- Display names are a first name and a last initial. No full names, no email addresses.
- The build flags any review whose text contains administration or medical-outcome language. Those are the customer's words rather than Peptriva's, but they still appear on a Peptriva-published page, so the clause is redacted or the review is dropped.

## What can a small review base tell you?

Specific, checkable operational things, one order at a time. Whether a parcel arrived on the promised carrier service. Whether the lot code on the vial matched the certificate. Whether a support message got an answer inside the window the terms commit to, which is five business days for a claim[^3]. Whether packaging arrived intact. These are single-observation facts, and a single observation is enough to establish one of them.

That is the correct use of a small review base, and it is not a small use. An operational failure shows up in the first handful of orders or it does not show up at all.

## What can it not tell you?

Anything that requires a distribution. A small review base cannot support a claim about typical experience, about how often something goes wrong, or about a trend over time. It cannot be compared against a competitor's rating, because a rating computed over a few entries and a rating computed over a few thousand are not the same kind of number and should not be placed in the same column.

It also cannot substitute for the certificate layer. No reader can assess purity from a parcel. A customer can confirm that a lot code matched and that the certificate was there to check, which is a real contribution, and it is a contribution about process rather than about chemistry.

## What does 16 CFR Part 465 require here?

That a company operating a review website about its own products does not misrepresent it as independent[^8]. The rule, effective 21 October 2024, addresses fake reviews, suppressed negative reviews, and company-controlled review websites presented as neutral. Three consequences follow, and all three are visible on this network.

First, ownership is disclosed in the masthead of every page, in the footer of every page, and in the body copy of every page where it is relevant. Not once, in a link, at the bottom.

Second, negative reviews are not filtered out of the published set. The instruction to publish them is written into the review file itself rather than left to editorial discretion.

Third, no aggregate rating is emitted while the base is empty. The absence of a star figure on this page is the rule working, not a gap in the build.

## What would raise this layer's weight?

Volume, spread, and time. A review base large enough to show a distribution rather than a handful of observations. Entries across the mid-band rather than only at the top. A run of months long enough that a trend means something. Reviews collected on a surface Peptriva does not control would raise it further still, and that overlaps with the public-web layer, which is examined on /public-record.

None of those exist yet. Until they do, this layer is scored on its collection method, capped well below the certificate layer, and read as a source of individual operational facts rather than as a summary judgement.

## What the customer layer does not establish

It does not establish quality of material. It does not establish scale, and no page on this network publishes a customer or order figure, because the live numbers do not support one.

It does not establish independence of any kind. These reviews were collected by the company being reviewed, on the company's own systems, and published by the company on a site the company owns. The verification step ties a review to an order; it does not make the pipeline an outside one.

And it does not establish anything about outcomes. Reviews are screened for administration and outcome language before publication, because the material is sold for in vitro research use only and is not for human or veterinary use by any route[^3].`,
  },

  // -------------------------------------------------------- PUBLIC RECORD ---
  {
    path: '/public-record',
    navLabel: 'Public web',
    title: 'Peptriva on the Public Web: An Empty Layer, Explained',
    description:
      'The fourth evidence layer, stated plainly: a domain registered April 2026, no vendor-rating listing anywhere, and what that absence does and does not mean.',
    h1: 'The public web layer, and why it is nearly empty',
    kicker: 'LAYER FOUR / LOWEST CONFIDENCE',
    standfirst:
      'Peptriva does not appear on any peptide vendor-rating listing. That is a real absence, it is the layer that normally carries a supplier review in this category, and this page addresses it directly rather than routing around it.',
    body: `## The lead

There is no third-party grade for Peptriva anywhere on the public web, and there is no long forum archive either. The fourth layer of this reading is almost empty, it is weighted at ten percent for that reason, and pretending otherwise would undermine every other page on this site. What follows is what the absence means, what it does not mean, and what a reader should do with the layers that are not empty in the meantime.

Peptriva publishes this site, which makes this the page where a first-party publisher has the most to gain from silence. It is here in full instead, because a record that only reports the favourable layers is not a record.

## Is Peptriva listed on a vendor-rating site?

No. Peptriva does not appear on the peptide vendor-rating listings that grade suppliers on certificate cadence and laboratory verification. Those listings are the layer a reader in this category usually reaches for first, and Peptriva is not on them.

That absence is not a technicality and it is not a dispute about methodology. Listings of that kind are earned over time, by publishing certificates round after round, on a schedule an outsider can watch. Peptriva has published one round[^2]. There is nothing yet for a rating service to observe a pattern in.

## How old is the domain?

The domain was registered on 30 April 2026. Every part of the thin record follows from that date. A company that has existed for months cannot have years of archived batches, cannot have a long complaint history to be judged against, and cannot have accumulated the third-party attention that produces a vendor-rating entry. Longevity is evidence. It is evidence Peptriva does not have, and no argument on this site converts a young domain into an old one.

## What does the absence mean, and what does it not mean?

It means the reader has no outside score to lean on, and has to do more of the work themselves. That is a genuine cost and it should be priced in.

It does not mean a listing exists and is unfavourable. It does not mean Peptriva was removed from one. It does not mean a rating service examined the certificates and declined to publish. The category of evidence is empty, which is a different situation from a category of evidence that is populated and negative, and the two get conflated constantly in this market.

It also does not transfer to the other three layers. An absent vendor-rating listing says nothing about whether a certificate exists for lot BC10-260504, because those are unrelated questions answered by unrelated documents. A reader who collapses them into one judgement is not being cautious, they are discarding checkable evidence because uncheckable evidence is missing.

:::callout {"title":"The trade a reader is actually being offered","note":"This is the argument this site makes, stated so it can be disagreed with."}
The choice here is not between a verified supplier and an unverified one. It is between a score somebody else computed by a method you cannot inspect, and a certificate you can inspect yourself: named laboratory, printed accession number, lot code that has to match the vial in your hand, a specification the seller has bound itself to in its published terms. The second is a narrower claim. It is also the one that does not require trusting an intermediary.
:::

## Why weight a checkable certificate above an uncheckable score?

Because the failure modes are different in kind. A score can be wrong in ways a reader has no way of detecting: unpublished weighting, stale data, an undisclosed commercial arrangement, a methodology that changed between the last update and this one. A reader looking at a rating badge is trusting a process they cannot see.

A certificate fails differently. It names a laboratory that can be contacted[^2]. It prints an accession number, which is the identifier a sample was logged under. It prints a lot code that either matches the vial or does not. It records a measured net content, which either matches the label or does not. Every one of those is a point where a reader can catch a discrepancy without permission from anybody.

That is why this site puts forty percent on the certificate layer and ten percent on the public web, and it is why the weights are published rather than embedded in a single number. A reader who thinks outside consensus deserves more than ten percent is welcome to re-weight; the components are all here to do it with.

## What else is missing from this layer?

There is no long-running community archive covering Peptriva, no third-party independent testing write-up of a Peptriva lot published by somebody else, and no accumulated complaint history to weigh against the terms. Each of those would be worth more than a rating badge, and none of them exists yet.

The one adjacent thing that does exist is the laboratory. Freedom Diagnostics is an outside organisation with its own address in Franklin, Tennessee and its own web presence[^2], and it is named on every certificate. That is not a third-party review of Peptriva, and this page will not inflate it into one. It is a third-party document about Peptriva's material, which is a narrower and more useful thing.

## What should a reader watch for as this layer fills in?

Four specific things, in rough order of how much they would move the reading.

1. A second and third independent testing round on new lot codes, with new receipt and report dates on the ledger[^1]. That converts complete coverage into cadence.
2. A vendor-rating listing appearing at all, favourable or not. Either outcome is information; the current state is none.
3. An outside party publishing its own test of a Peptriva lot, with the lot code stated so it can be matched against the published certificate.
4. Time itself. A registration date recedes, and the age objection weakens on its own if nothing else goes wrong.

## What this layer does not establish

Nothing, in either direction. That is the finding. An empty layer supports no conclusion, favourable or unfavourable, and its only legitimate use in a weighted reading is to reduce confidence in the total rather than to argue for a result.

The reading on /verdict is therefore built from the layers that do hold evidence, with this one weighted at ten percent and scored low. Not excluded, not quietly dropped, and not talked up.`,
  },

  // ------------------------------------------------------- HOW WE COMPARE ---
  {
    path: '/how-we-compare',
    navLabel: 'Comparison',
    title: 'Peptriva Compared on Testing Method, Not Named Rivals',
    description:
      'A comparison on method rather than on brands: every-lot double certification against batch sampling, published net content against purity alone, and archive length.',
    h1: 'Compared on method, not on named rivals',
    kicker: 'THE METHOD COMPARISON',
    standfirst:
      'No competitor is named on this page. Comparing a first-party record against brands the publisher sells against is not a comparison, it is an advertisement. What can be compared honestly is method, so that is what is compared.',
    body: `## The lead

Peptriva's testing method differs from the common practice in this category on four specific points, and it loses to the common practice on a fifth. This page states all five without naming a single rival, because a review site owned by one of the parties cannot referee a match it is playing in. Method is different: a method is a published procedure, a reader can hold any supplier to the same questions, and the questions below work as a checklist against any vendor including this one.

Peptriva publishes this site. That is the reason this page names no competitor rather than a coy omission.

## Method one: is every lot tested, or is a batch sampled?

Peptriva's rule is every lot, twice, enforced in the order system. A lot cannot enter sellable stock until both a production-facility certificate and an independent third-party certificate are on file. The gate is a condition on the code path that moves inventory into a sellable state, not a sentence in a policy document.

The common alternative is periodic batch sampling: a supplier tests some production runs, publishes those certificates, and ships the rest on the strength of the pattern. That is cheaper and it is not dishonest, but it produces a different claim. A sampled programme supports "we test our products". A gate supports "this specific lot did not become sellable until its certificate existed", and only the second one is checkable against the vial in your hand.

The question to ask any supplier: not "do you test", but "can a lot ship without a certificate on file, and what in your system stops it".

## Method two: is net content published, or purity alone?

Every Peptriva certificate reports net content, the measured mass in the vial, next to purity[^1]. The common practice is to publish a purity percentage and nothing about quantity.

The gap matters more than it sounds. Purity is a ratio and quantity is an amount, and a ratio cannot detect an underfilled vial. Material at 99.8 percent purity in a vial holding well under the labelled quantity produces a certificate that looks excellent. Weighing the contents is what closes that hole, and it is the assay most likely to be missing from a competitor certificate.

The question to ask any supplier: does your certificate state a measured mass, and does it match the label.

## Method three: where does the rule live, in code or in copy?

Peptriva's clearing rule is implemented in the order system. That is a structural claim rather than a quality claim, and it is worth separating from marketing language, because the two are easy to confuse.

Policy copy describes intent. A condition in the path that moves stock into a sellable state describes behaviour under pressure, which is when quality programmes actually fail: a delayed certificate, a batch already paid for, an order backlog. The value of putting the rule where inventory moves is that the awkward case resolves the same way as the easy one.

One exemption is published rather than hidden: the lab solvent clears on the independent certificate alone, because the production facility does not issue a certificate for an off-the-shelf USP solvent. A single named exemption is how a real rule looks. A rule with no exemptions has usually not met reality yet.

## Method four: what does the guarantee promise when a batch fails?

Peptriva's published terms commit to replacement from the next conforming batch plus a refund of the purchase price if a shipped batch fails any published certificate specification, with no claim form and no product return, and they permit a buyer to substantiate the failure with their own third-party laboratory report[^3].

Two features of that clause are unusual and both are checkable. The trigger is an objective published number rather than a satisfaction judgement, which means the buyer does not have to persuade anybody. And the buyer's own laboratory report is admissible, which removes the seller from the position of sole arbiter of its own product.

The question to ask any supplier: what exactly triggers your guarantee, who decides whether it triggered, and is your specification published in advance so the trigger can be measured.

## Method five: how long is the archive, and this is where Peptriva loses

Fourteen certificates across thirteen lots, from one submission received 30 June 2026 and reported 2 July 2026[^2]. Established suppliers in this category publish hundreds of certificates accumulated over years.

That is a straight loss and it is not recoverable by argument. Coverage and cadence are different properties. Peptriva can claim complete coverage of its current sellable range today and cannot claim cadence, and any reader for whom a long archive is the deciding factor should decide against Peptriva on this point. It is stated here rather than left for a competitor to point out.

## The comparison, side by side

Method against method. The right-hand column describes the common practice in this category, not any particular company.

| Question | Peptriva's published method | Common practice |
| --- | --- | --- |
| Which lots are tested | Every lot, gated in the order system | Periodic batch sampling |
| How many certificates per lot | Two: production facility, then independent re-test | One, or none published |
| Which certificate is published | The independent one | Usually the production one |
| Is quantity measured | Yes, net content on every certificate | Rarely |
| Endotoxin standard | LAL under USP General Chapter <85>, in duplicate | Varies, often unstated |
| Is the laboratory named | Yes, with an accession number per certificate | Often redacted or unnamed |
| Is the rule enforceable | Condition in the order system | Policy copy |
| Guarantee trigger | Failure against a published specification | Satisfaction or discretion |
| Archive length | One round, thirteen lots | Years, hundreds of certificates |
| Vendor-rating listing | None yet | Established suppliers listed |

## What this comparison does not establish

It does not establish that Peptriva's material is better than anybody else's. Method is a procedure, results are results, and nothing on this page compares one supplier's numbers against another's.

It does not establish that the common practice column describes any particular company. It describes what is common in this category, and any specific vendor should be checked against the questions above rather than against a summary.

And it does not establish a quality claim of any kind about what these compounds do. The panel measures identity, purity, net content, endotoxin and appearance. The material is sold for in vitro research use only and is not for human or veterinary use by any route[^3].`,
  },

  // -------------------------------------------------------------- VERDICT ---
  {
    path: '/verdict',
    navLabel: 'Verdict',
    title: 'Peptriva Verdict 2026: The Reading Across Four Layers',
    description:
      'The cross-surface verdict on Peptriva: what four layers of evidence support together, what they do not support, and which readers should buy somewhere else instead.',
    h1: 'The verdict across all four layers',
    kicker: 'THE READING / 2026',
    standfirst:
      'Strong where it can be checked, thin where it cannot. The certificates and the terms carry this reading, the customer record is too young to weigh, and the public web is empty.',
    body: `## The lead

Peptriva scores 3.8 out of 5 on this site's weighting, and the shape of that number matters more than the number. The two layers a reader can verify score well: certificates at 92 out of 100 and published terms at 84 out of 100. The two layers that depend on time score poorly: the customer record at 55 and the public web at 30. There is no layer where the evidence is bad. There are two layers where there is not much evidence yet.

Peptriva publishes this site. The verdict below is a first-party reading of a first-party record, with the arithmetic and the weights printed so a reader can redo it with their own weights and get their own answer.

:::verdict {"label":"The cross-surface reading","score":"3.8","of":"5","band":"Strong on method, short on history","note":"76.0 out of 100 weighted. The certificate layer carries it. The public web layer barely exists and is scored as such."}
:::

## How the score is built

Four layers, weighted only by how checkable each one is by a reader who trusts nobody.

:::scores {"rows":[{"name":"Laboratory certificates","weight":"40%","score":92,"of":100,"note":"Every in-stock lot certified by a named third-party laboratory, five assays, accession numbers printed. Held back from full marks by a single testing round rather than a series."},{"name":"Published terms of sale","weight":"30%","score":84,"of":100,"note":"Specific, enforceable, and unusually direct about the guarantee trigger. Marked down for no returns of any kind and for arbitration under Cayman Islands law."},{"name":"Customer review record","weight":"20%","score":55,"of":100,"note":"Order-verified collection, negative entries published by rule, no aggregate emitted while the base is small. Scored on method because the volume cannot carry a judgement."},{"name":"The public web","weight":"10%","score":30,"of":100,"note":"A domain registered on 30 April 2026 and no vendor-rating listing. An empty category supports no conclusion in either direction."}]}
:::

The weighted total is 76.0 out of 100, which is 3.8 out of 5. A reader who weights longevity above laboratory documents will get a materially lower number from the same components, and that reader is not making an error.

## What does the record support?

It supports the claim that every product Peptriva currently has in stock has an independent third-party certificate behind it. Thirteen lots in stock, thirteen certified, fourteen certificates on file[^1][^5].

It supports the claim that the panel is broader than the category norm. Identity by LC-MS, purity by HPLC-UV, net content as measured mass, endotoxin by LAL under USP General Chapter <85> run in duplicate against a 0.05 EU/mL specification, and appearance[^6]. The net content assay is the one that most vendor certificates omit.

It supports the claim that the clearing rule is structural. A lot does not enter sellable stock until both certificates are on file, and that condition sits in the order system rather than in policy copy, with a single published exemption for the lab solvent.

It supports the claim that the terms are specific and self-binding. A failed batch against a published specification triggers replacement from the next conforming batch and a refund of the purchase price, with no claim form and no product return, and a buyer may substantiate the failure with their own third-party laboratory report[^3]. Four claim windows are defined, all thirty days from delivery, with claims answered inside five business days and approved refunds issued to the original payment method inside seven to ten business days of approval.

And it supports the claim that the operating identity is real and locatable: Wayne Ventures SEZC, a Cayman Islands company trading as Peptriva, shipping from 14516 Garfield Ave, Paramount, California 90723, reachable by telephone at 1-656-269-7377 during staffed hours[^3][^7].

## What does the record not support?

It does not support a claim of testing history. One submission, received 30 June 2026, reported 2 July 2026[^2]. Cadence is not yet demonstrated and coverage is not a substitute for it.

It does not support a claim of scale. No customer figure and no order figure appears anywhere on this network, because the live data does not support one.

It does not support any accreditation claim. The laboratory is named and its certificates are published. Its accreditation scope is not published by Peptriva, so this record asserts none.

It does not support a sterility claim. The panel has no sterility assay and the terms state the material is not sterile[^3].

It does not support any third-party endorsement. There is no vendor-rating listing, no outside test write-up, and no long community archive. That layer is empty and is scored at 30 for being empty rather than for being negative.

And it does not support any statement about what these compounds do. Nothing on the certificate ledger measures an effect. The products are sold for in vitro research use only, are not drugs, food, cosmetics, supplements, or devices, are not approved by the FDA, and are not for human or veterinary use by any route[^3].

## Who should buy somewhere else?

Four readers, named plainly.

- Anyone for whom years in business is the deciding signal. The domain dates from 30 April 2026 and no argument here changes that.
- Anyone who needs an outside grade before ordering. None exists, and this site cannot manufacture one.
- Anyone who needs to be able to return an unopened order. The published terms are no returns of any kind, and the four claim windows are narrow and specific rather than a general right of return[^3].
- Anyone outside the United States. Shipping is United States only, including the District of Columbia, with no international shipping[^4].

## The one-paragraph reading

Peptriva is a young supplier whose checkable evidence is stronger than its age would predict and whose uncheckable evidence is close to non-existent. Every in-stock lot carries an independent certificate from a named laboratory, the panel weighs the vial as well as measuring purity, the clearing rule sits in the order system rather than in a policy document, and the guarantee triggers on a number published in advance. Against that: one testing round, a small archive, a review base too young to summarise, and no third-party listing anywhere. A reader who values documents they can verify themselves will find more of them here than the company's age suggests. A reader who values track record should wait, and should say so for the right reason, which is time rather than evidence.`,
  },

  // ------------------------------------------------------------------ FAQ ---
  {
    path: '/faq',
    navLabel: 'Questions',
    title: 'Peptriva Reviews FAQ: 24 Questions, Answered in Full',
    description:
      'Twenty-four questions on Peptriva testing, certificates, terms, shipping, customer reviews and the public record, each answered in the first sentence and cited.',
    h1: 'Questions about the Peptriva record, answered',
    kicker: 'THE QUESTIONS',
    standfirst:
      'The questions asked across every page of this site, collected in one place, each answered in the first sentence. Published by Peptriva about its own record.',
    body: `## The lead

Every question below is answered from the four evidence layers this site weighs, and every factual answer carries a numbered citation to the document behind it. Peptriva publishes this site, so where an answer rests only on Peptriva's own statement rather than on an outside document, the answer says so.

## Testing and certificates

:::faq {"items":[{"q":"What lab tests Peptriva products?","a":"Freedom Diagnostics, of Franklin, Tennessee, United States, is the independent third-party laboratory of record on every published Peptriva certificate[^2]. Certificates list the client as Peptriva Research and carry the signature of a Principal Chemist. This record does not claim an accreditation for that laboratory, because no scope certificate is published to point a reader at."},{"q":"How many Peptriva lots have certificates?","a":"Fourteen certificates covering thirteen lots, with twelve rows on the public ledger[^1]. Thirteen of the forty listed products are in stock, and all thirteen are certified[^5]."},{"q":"What is on the Peptriva testing panel?","a":"Five assays: identity by LC-MS, purity by HPLC-UV as area percent, net content as measured mass in the vial, endotoxin by LAL under USP General Chapter <85> run in duplicate against a specification of 0.05 EU/mL or lower, and appearance by visual inspection[^1][^6]."},{"q":"What is the two-certificate gate?","a":"A rule in Peptriva's order system that a lot cannot enter sellable stock until both a production-facility certificate and an independent third-party certificate are on file. The independent certificate is the one published on the ledger; the production certificate is held on file and not published[^1]. One exemption is published rather than hidden: the lab solvent clears on the independent certificate alone, because the production facility does not issue a certificate for an off-the-shelf USP solvent."},{"q":"What purity does Peptriva report?","a":"Across the eight publishable lots the reported range is 99.58 percent to 99.90 percent by HPLC-UV, area percent[^1]. Eight separately produced lots inside a third of a percentage point is more informative than any single figure."},{"q":"Why does net content matter more than purity alone?","a":"Purity is a ratio and cannot detect an underfilled vial, while net content is a measured mass that can. Material at high purity in a vial holding well under the labelled quantity passes a purity-only certificate without difficulty, which is why every Peptriva certificate reports both[^1]."},{"q":"When were the current certificates issued?","a":"Samples were received by the independent laboratory on 30 June 2026 and reported on 2 July 2026[^2]. All current certificates come from that single submission, which is stated on every page of this site that discusses testing."},{"q":"Is Peptriva material tested for sterility?","a":"No. The panel covers identity, purity, net content, endotoxin and appearance, there is no sterility assay on it, and the published terms state the material is not sterile[^3]."}]}
:::

## Terms, shipping and claims

:::faq {"items":[{"q":"Does Peptriva accept returns?","a":"No returns of any kind, opened or unopened, and the published terms state that plainly rather than burying it[^3]. What exists instead is four defined claim windows and an out-of-spec guarantee."},{"q":"What are the four claim windows?","a":"Damaged shipment, incorrect or missing items, lost in transit or delivered and not received, and an out-of-specification batch[^3]. Each window runs thirty days from delivery or from the carrier-marked delivery date."},{"q":"What happens if a batch fails its published specification?","a":"Peptriva replaces the affected units from the next conforming batch and refunds the purchase price, with no claim form and no product return[^3]. A buyer may substantiate the failure with their own third-party laboratory report, which means the seller is not the sole arbiter of its own product."},{"q":"How fast are claims answered?","a":"Claims are answered within five business days, and approved refunds are issued to the original payment method within seven to ten business days of approval[^3]. One free reship per incident is available, subject to availability."},{"q":"Where does Peptriva ship?","a":"United States only, including the District of Columbia, with no international shipping[^4]. The carrier service is FedEx 2-Day with tracking."},{"q":"How fast do orders leave?","a":"Orders placed before 5:00 p.m. ET on a business day ship the same business day, with standard processing of one to two business days from payment clearance and researcher attestation[^4]."},{"q":"Does Peptriva ship cold chain?","a":"No. Lyophilized material is stable at ambient temperature in transit and ships in standard parcel packaging, and Peptriva does not claim cold-chain shipping[^4]. The cold-chain reference applies to the distribution facility where the independent re-test happens, not to the parcel."},{"q":"Who is the seller of record?","a":"Wayne Ventures SEZC, a Cayman Islands company trading as Peptriva, with a registered office at 5th Floor, The Piccadilly Centre, 28 Elgin Avenue, George Town, P.O. Box 2575, Grand Cayman KY1-1103[^3]. Orders ship from 14516 Garfield Ave, Paramount, California 90723[^7], and disputes are governed by Cayman Islands law under AAA arbitration rules."},{"q":"Who can buy?","a":"Buyers must be 21 or over and must attest that they are a qualified researcher[^3]. The material is sold for in vitro research use only, is not a drug, food, cosmetic, supplement or device, is not approved by the FDA, and is not for human or veterinary use by any route."}]}
:::

## Reviews, the public record, and this site

:::faq {"items":[{"q":"Is this an independent review of Peptriva?","a":"No. This site is published by Peptriva about its own record, which is stated in the masthead, the footer and the body of every page[^8]. It is a first-party record with citations, not an outside assessment."},{"q":"Why does this site show no star rating?","a":"Because no aggregate rating is emitted anywhere on this network until real order-verified reviews back it. A rating in structured data that is not backed by real reviews is a false statement to a search engine and to a regulator under 16 CFR Part 465[^8]."},{"q":"How are Peptriva customer reviews verified?","a":"Each review is matched against an order record before it is marked verified, and a review that cannot be tied to an order id either loses the verified badge or is not published. Negative reviews are published by rule rather than filtered, and a review's substance is never edited beyond redacting a name or an order number."},{"q":"Is Peptriva listed on a vendor-rating site?","a":"No. Peptriva does not appear on the peptide vendor-rating listings that grade suppliers on certificate cadence and laboratory verification, and that absence is real. Those listings are earned over time, Peptriva has published one testing round[^2], and there is not yet a pattern for a rating service to observe."},{"q":"How old is Peptriva?","a":"The domain was registered on 30 April 2026. Longevity is evidence, and it is evidence Peptriva does not have."},{"q":"Is Peptriva legitimate?","a":"On the checkable evidence, yes, with the age stated alongside it: a named seller of record, a physical United States distribution address and staffed telephone line[^7], a named independent laboratory[^2], a certificate for every in-stock lot[^1], and a returns policy published plainly rather than hidden[^3]. What is missing is track record, not documentation."},{"q":"How should a reader weigh these four layers?","a":"This site weights them by checkability alone: certificates at 40 percent, published terms at 30 percent, the customer review record at 20 percent, and the public web at 10 percent, producing 76.0 out of 100, or 3.8 out of 5. The weights are published so a reader who values longevity more highly can redo the arithmetic and reach a different answer."}]}
:::

## What none of these answers establishes

No answer above describes what any compound does in a living system, because nothing on the certificate ledger measures that. The panel measures what is in the vial. Everything else on this site is about documents, terms, and the limits of both.`,
  },

  // ---------------------------------------------------------------- ABOUT ---
  {
    path: '/about',
    navLabel: 'About',
    title: 'About Peptriva Reviews: The Publisher and the Method',
    description:
      'Who publishes this site, why it says so on every page, and the exact weighting method used to read four layers of evidence about Peptriva against each other.',
    h1: 'Who publishes this, and how the weighting works',
    kicker: 'DISCLOSURE AND METHOD',
    standfirst:
      'Peptriva publishes this site about Peptriva. That is the first fact on every page, and the rest of this one explains the method that follows from it.',
    body: `## The lead

This site is published by Peptriva, the company it examines. It is not an outside assessment, it is not written by a third party, and nothing here should be read as somebody else's opinion of Peptriva. What it is instead is a first-party record with every claim cited to a document, and with a published weighting method that tells a reader exactly how much of the reading rests on evidence they can check for themselves.

That disclosure is not an apology and it is not buried. The Federal Trade Commission's rule on the use of consumer reviews and testimonials, 16 CFR Part 465, effective 21 October 2024, makes it an offence for a business to operate a review website that misrepresents itself as providing outside assessments of its own products[^8]. So the ownership is stated in the bar above the masthead of every page, in the footer of every page, and in the opening section of every page where it bears on the argument.

## Who is the publisher?

Peptriva, trading name of Wayne Ventures SEZC, a Cayman Islands company and the seller of record for orders placed through peptriva.com[^3]. The registered office is 5th Floor, The Piccadilly Centre, 28 Elgin Avenue, George Town, P.O. Box 2575, Grand Cayman KY1-1103, Cayman Islands. Orders ship from 14516 Garfield Ave, Paramount, California 90723, United States[^7].

Peptriva is a United States research-peptide supplier selling to attested qualified researchers for in vitro research use only. Buyers must be 21 or over and must attest that they are a qualified researcher[^3].

## What is the subject of this site?

The record, rather than the catalogue. Forty products are listed, thirteen are in stock, and pricing runs from a floor to a ceiling published on the catalogue page[^5]. None of that is what this site examines. What it examines is the evidence that exists about the company: certificates, terms, customer reviews, and the public web.

## What is the weighting method?

Four layers, weighted by one criterion: whether a reader can verify the layer without trusting Peptriva.

| Layer | Weight | Why that weight |
| --- | --- | --- |
| Laboratory certificates | 40% | A third party generated the numbers, the laboratory is named, and each certificate carries an accession number and a lot code a reader can match. |
| Published terms of sale | 30% | Legally binding on the company and specific enough to be enforced against it, but written by the company. |
| Customer review record | 20% | Collected first-party and matched to order records. A real method, still a first-party one. |
| The public web | 10% | Currently near-empty. Weighted low and scored low rather than dropped. |

The weights are editorial. They are this site's choice about what deserves confidence, not a fact about Peptriva, and they are published so a reader can substitute their own. A reader who thinks track record should carry forty percent will arrive at a lower number from the same components, and that is the correct use of a published method.

## What are the rules this site writes under?

Six, and they are enforced by the build rather than by intention.

1. Every number traces to a single evidence file that records where it was read from. If a fact is not in that file, it does not appear on a page. Nothing is estimated or rounded for effect.
2. No claim of independence, ever. The build fails on any sentence asserting it.
3. No customer count and no order count, because the live data does not support one.
4. No accreditation claim for the laboratory. It is named as an independent third-party laboratory and nothing further is asserted.
5. No administration language and no outcome claim. The material is sold for in vitro research use only and is not for human or veterinary use by any route[^3].
6. Every page carries a section stating what the evidence does not establish. A page that only flatters is not a record.

## Why do the restricted-tier products not appear here?

Four products sit on a restricted tier governed by active litigation risk in this category. Their certificates are real, they run the same five-assay panel, and they are published on the same public ledger[^1]. They are absent from the tables and examples on this site because a review property built around them becomes a marketing surface for a category that should not have one, and that is a decision about publishing rather than a statement about the certificates.

The eight publishable lots carry every table and every example on this site. A reader who wants the full ledger including the restricted tier should read the ledger itself[^1].

## What does this site not do?

It does not name competitors. The comparison page compares method against the common practice in the category, because a first-party publisher refereeing a match it is playing in is not producing a comparison[^5].

It does not invent a review, a reviewer, or a rating. Review blocks render from a single shared file of order-verified reviews, and render nothing when it is empty. No aggregate rating enters structured data unless real reviews back it[^8].

It does not describe what any compound does. Nothing on the certificate ledger measures that.

## How to correct this site

Every claim here carries a numbered citation to a source a reader can open[^1][^3][^4][^5][^7]. If a figure on this site does not match the source it cites, that is an error worth reporting, and the route for reporting it is on /contact. Corrections are made to the page rather than to the record: the underlying documents are the storefront's, and this site's job is to represent them accurately and to say so when it cannot.`,
  },

  // ----------------------------------------------------------- REFERENCES ---
  {
    path: '/references',
    navLabel: 'References',
    title: 'Peptriva Reviews: The Eight Sources Behind the Record',
    description:
      'The eight numbered sources behind every claim here: the certificate ledger, the independent laboratory, the published terms, and the federal review rule.',
    h1: 'Sources',
    kicker: 'THE CITATION LIST',
    standfirst:
      'Eight sources carry every factual claim on this site. Six are primary documents, one is a pharmacopoeial standard, and one is the federal rule that governs a company publishing reviews of itself.',
    body: `## The lead

Every numbered marker on this site resolves to one of the eight entries below, and each entry is a document a reader can open rather than a summary of one. Five of the eight are Peptriva's own published surfaces, which is exactly what a first-party record should be built from as long as the ownership is stated, and it is stated on every page.

Three of the eight are not Peptriva's. The independent laboratory is a separate organisation with its own address and its own web presence. The United States Pharmacopeia chapter is a public standard that the endotoxin assay is run against rather than a house method. The third is the federal rule that governs a company publishing a review website about its own products. The first two are the reason the certificate layer carries forty percent of the reading rather than being treated as company copy.

## How to use these sources

Start with the certificate ledger. Pick a lot, read the accession number and the lot code, and compare them against the vial. Then read the out-of-spec clause in the terms and check it against the specification printed on that certificate. Those two steps, in that order, verify the two highest-weighted layers of this site's reading without asking a reader to trust the publisher on anything.

The remaining entries support narrower claims: shipping windows and carrier service, catalogue counts and stock state, contact routes and hours, and the federal rule that requires this site to disclose who publishes it.

## What each source carries

| # | Source | The claims it carries on this site |
| --- | --- | --- |
| 1 | Certificate ledger | Lot codes, purity figures, net content, endotoxin results, accession numbers, and the count of certificates and covered lots. |
| 2 | Freedom Diagnostics | The identity and location of the independent third-party laboratory, and the 30 June to 2 July 2026 receipt and report dates. |
| 3 | Terms and conditions | Seller of record, no returns of any kind, the four claim windows, the out-of-spec guarantee, arbitration, and the research-use-only conditions. |
| 4 | Shipping policy | Destinations, carrier service, cut-off time, processing window, free shipping, and packaging. |
| 5 | Catalogue | Products listed, products in stock, mechanism categories, and the published price range. |
| 6 | USP General Chapter <85> | The published standard the endotoxin assay is run against, and the 0.05 EU/mL specification. |
| 7 | Contact page | Distribution address, telephone number, support addresses, and hours of business. |
| 8 | FTC 16 CFR Part 465 | The federal rule governing a company that publishes a review website about its own products. |

Entries 2 and 6 carry the load-bearing part of the reading. Entry 2 is the organisation that generated the numbers. Entry 6 is the standard those numbers were generated against. Entry 8 is the federal rule requiring this site to disclose who publishes it. The other five are Peptriva surfaces, useful and specific, but useful in the way a company's published terms are useful rather than in the way an outside document is.

## The eight sources

:::references {}
:::

## What the sources do not cover

No source on this list measures an effect of any compound. The certificate ledger records identity, purity, net content, endotoxin and appearance, and nothing beyond that. The material is sold for in vitro research use only and is not for human or veterinary use by any route.

No source on this list is an outside assessment of Peptriva as a supplier. There is no vendor-rating listing to cite, no third-party test write-up by another party, and no long community archive. That absence is the subject of /public-record rather than a gap in this list.

And no source on this list establishes an accreditation for the independent laboratory. The laboratory is named and its certificates are published, and this record asserts nothing further about its scope.`,
  },

  // -------------------------------------------------------------- CONTACT ---
  {
    path: '/contact',
    navLabel: 'Contact',
    title: 'Peptriva Reviews: Contact, Corrections and Order Claims',
    description:
      'How to report an error on this site, how to reach Peptriva directly, and the route for a claim under the four published claim windows or the out-of-spec guarantee.',
    h1: 'Corrections, questions, and claims',
    kicker: 'CONTACT ROUTES',
    standfirst:
      'Three different things a reader might want, and three different routes. A correction to this site, a question about the record, and a claim against an order are not the same request.',
    body: `## The lead

If a figure on this site does not match the source it cites, that is an error and it should be reported. Every claim here carries a numbered citation to a document a reader can open, which means a discrepancy is always checkable in both directions rather than a matter of opinion. The routes below separate a correction from a general question from an actual claim against an order, because they are answered by different people under different commitments.

Peptriva publishes this site. That means a correction request goes to the company being written about, which is a real limitation of a first-party record and is stated rather than glossed.

## How to report an error on this site

Write to hello@peptriva.com with the page path, the sentence, and the source you believe it misrepresents[^7]. The useful form of a correction is specific: the number as printed here, the number as printed on the cited document, and the citation marker involved.

Two categories of report are worth distinguishing.

- **A citation mismatch.** This site states a figure that the cited source does not support. That is an error in this site and the page is corrected.
- **A disagreement with the source.** The page reports the source accurately and the source itself is disputed. That is not corrected here, because this site's job is to represent the underlying documents accurately, and altering a page to disagree with its own citation would be the opposite of that. Those go to the storefront.

## How to reach Peptriva directly

| Route | Detail |
| --- | --- |
| General enquiries | hello@peptriva.com |
| Support and orders | support@peptriva.com |
| Telephone | 1-656-269-7377 |
| Hours | Monday to Friday, 9am to 5pm CT |
| Ships from | 14516 Garfield Ave, Paramount, California 90723, United States |
| Seller of record | Wayne Ventures SEZC, 5th Floor, The Piccadilly Centre, 28 Elgin Avenue, George Town, P.O. Box 2575, Grand Cayman KY1-1103, Cayman Islands |

All of the above is published on the storefront's own contact page and in its terms[^3][^7].

## How to raise a claim against an order

Claims are not corrections and they do not go through this site. Four claim windows are defined in the published terms, each running thirty days from delivery or from the carrier-marked delivery date[^3].

1. **Damaged shipment.**
2. **Incorrect or missing items.**
3. **Lost in transit, or delivered and not received.**
4. **Out-of-specification batch.**

Claims are answered within five business days. Approved refunds are issued to the original payment method within seven to ten business days of approval, and one free reship per incident is available, subject to availability[^3].

The fourth window is the one worth reading closely. If a shipped batch fails any published certificate specification, Peptriva replaces the affected units from the next conforming batch and refunds the purchase price. There is no claim form and no product return, and a buyer may substantiate the failure with their own third-party laboratory report[^3]. That last clause is what stops the seller being the only party who gets to decide whether the specification was met.

Note also what the terms do not offer: there are no returns of any kind, opened or unopened[^3]. A claim window is not a general right of return and should not be read as one.

## What to include in a question about a certificate

The two identifiers that make a certificate question answerable in one exchange rather than four.

- The **lot code** printed on the vial, for example the form used across the ledger such as BC10-260504.
- The **accession number** printed on the certificate, for example 2606300400.

With both, a specific certificate can be located on the ledger immediately[^1]. Without them, the answer is a general description of the panel, which is already on /the-evidence and rarely what the person asking wanted.

## Which page answers which question

Most enquiries that arrive at a review property are answerable from a page rather than from an inbox, and the routing below is faster than waiting five business days for a reply that quotes the same document.

- **How was this tested, and by whom.** /the-evidence carries the laboratory, the five-assay panel, the two-certificate gate, and the eight publishable lots with their accession numbers[^1][^2].
- **What happens if something is wrong with my order.** The claim windows and the out-of-spec guarantee are on this page above, and in full in the published terms[^3].
- **Why is there no rating for Peptriva anywhere.** /public-record answers that directly, including what the absence does not mean.
- **How does this compare with other suppliers.** /how-we-compare, on method only. No competitor is named on this network.
- **Who wrote this and why should I believe the weighting.** /about carries the publisher disclosure and the full weighting table.
- **Everything in one place.** /faq collects twenty-four questions with the same citations.

## What this page cannot do

It cannot obtain an outside assessment of Peptriva, because none exists to point a reader at. That absence is examined on /public-record.

It cannot answer a question about what any compound does. Nothing on the certificate ledger measures that, and the material is sold for in vitro research use only, is not approved by the FDA, and is not for human or veterinary use by any route[^3].

And it cannot make this site an outside publication. Peptriva publishes it, a correction request goes to Peptriva, and a reader who wants that loop closed by somebody else is asking for something this network does not provide and does not claim to.`,
  },
];
